name: LessGenerators
version: "2020.10-02"
license: "GPL-2.0-or-later"
date: 2020-10-17
description: |
    Find smaller generating sets for modules

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Anna Fabiańska
      url: http://wwwb.math.rwth-aachen.de/~fabianska/
    - name: Vinay Wagh
      url: http://www.iitg.ernet.in/vinay.wagh/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "AutoDoc"
      version: ">= 2013.08.07"
      url: "https://gap-packages.github.io/AutoDoc"
    - name: "Modules"
      version: ">= 2017.06.19"
      url: "https://homalg-project.github.io/homalg_project/Modules"
    - name: "homalg"
      version: ">= 2012.05.18"
      url: "https://homalg-project.github.io/homalg_project/homalg"
    - name: "RingsForHomalg"
      version: ">= 2017.06.21"
      url: "https://homalg-project.github.io/homalg_project/RingsForHomalg"
    - name: "LocalizeRingForHomalg"
      version: ">= 2013.07.15"
      url: "https://homalg-project.github.io/homalg_project/LocalizeRingForHomalg"
    - name: "MatricesForHomalg"
      version: ">= 2019.01.04"
      url: "https://homalg-project.github.io/homalg_project/MatricesForHomalg"
    - name: "GAPDoc"
      version: ">= 1.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://homalg-project.github.io/LessGenerators
readme: README.md
packageinfo: https://homalg-project.github.io/LessGenerators/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/LessGenerators/releases/download/v2020.10-02/LessGenerators-2020.10-02.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/LessGenerators/releases/download/v2020.10-02/LessGenerators-2020.10-02.zip

pdf: https://github.com/homalg-project/LessGenerators/releases/download/v2020.10-02/LessGenerators-2020.10-02.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    generators, minimal set of generators, heuristics, Quillen-Suslin.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BFW20</span>]   <b class='BibAuthor'>Barakat, M., Fabiańska, A. and Wagh, V.</b>,
     <i class='BibTitle'>LessGenerators, Find smaller generating sets for modules,
             Version 2020.10-02</i>
     (<span class='BibYear'>2020</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/LessGenerators">https://homalg-project.github.io/LessGenerators</a></span>.
    </p>
    

bibtex: |
    @misc{ LessGenerators2020.10-02,
      author =           {Barakat, M. and Fabia{\a'n}ska, A. and Wagh, V.},
      title =            {{LessGenerators},  Find  smaller  generating  sets for
                          modules, {V}ersion 2020.10-02},
      month =            {Oct},
      year =             {2020},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/LessGenerators}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{LessGenerators}}},
      keywords =         {generators;  minimal  set  of  generators; heuristics;
                          Quillen-Suslin},
      printedkey =       {BFW20}
    }

